# name used to describe the current config (used to save results, checkpoints, etc under this directory)
META_NAME : "train_tiled"

# the root directory containing the tile directory. 
INPUT_DIR : "input/TUPAC"

# directory containing the whole slide images
WSI_DIR : "train"

# path should be INPUT_DIR/META_NAME/IMG_DIR
IMG_DIR : "tiles"

# path should be INPUT_DIR/META_NAME/LABEL_DIR
LABEL_DIR : "labels"

# max tile dimensions allowed
MAX_IMG_SIZE : (224, 224)

TILE_SIZE : 224

# train:dev:test split in percentages.
SPLIT : [80, 10, 10]

# to enable generation of wsi images marked with the location of the mitotic activity (using label files)
PRE_VISUALIZE : False

# directory to save the visualizations enabled using PRE_VISUALIZE
VIS_DIR : "train_vis"

# to enable pretraining of the alexnet model
PRETRAIN : True

LEARNING_RATE : 0.03

# L2 regularization used to prevent overfitting.
L2_REG : 0.0003

# max number of epochs that was allowed for the model to be trained.
MAX_EPOCH : 100

# to enable randomizing train set every epoch.
RANDOMIZE_TRAIN : True

# dictionary of labels
PURE_LABELS : {"mitosis": 0, "no-mitosis": 1}

# number of labels to train for.
NUM_LABELS : 2

MEAN : [0.485, 0.456, 0.406]

STD : [0.229, 0.224, 0.225]

# early stopping if the network does not improve after these number of epochs
TRAIN_TILL_EPOCH : 40

# multiprocessing the image loading and performing minor image preprocessing
NUM_WORKERS : 8

# number of mini-batches used.
BATCH_SIZE : 2

# root dir to store the results
RES_DIR : "results"

# path should be RES_DIR/META_NAME/XYZ_RES_FILE
TEST_RES_FILE : "test_results.txt"

DEV_RES_FILE : "dev_results.txt"

TRAIN_RES_FILE : "train_results.txt"

ULTI_RES_FILE : "ulti_results.txt"

MODEL_SAVE_FILE : "save.m"

CHECKPOINT_FILE : "checkpoint.dict"